server:
  port: 81
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 10m
spring:
  session:
    redis:
      namespace: spring:session
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: aaaa
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ENC(gVSJoDlh+6wfZaWmNVVZHA==)
    password: ENC(SNqGTenuY+yc9I5CHb8sBQ==)
mybatis:
  type-aliases-package: com.hana.app.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
app:
  url:
    serverurl: http://172.16.21.242:80
  dir:
    imgdir: file:/Users/a1234/Desktop/hanaspring/imgs/
    logdir: file:/Users/a1234/Desktop/hanaspring/logs/
    imgsave: /Users/a1234/Desktop/hanaspring/imgs/
  key:
    wkey: Mpd6Rvm3BMLZFpbl%2FJdLLpW83sfGhRtP2CTabpRjSzuBHHqSUCDfJYt7BxoozPt7lrLZ9iTDITtVLDvh%2F1ei9Q%3D%3D
    whkey: 5ae7c11283db62206e0b6552195f7bce
    ncp-id: fy27808voy
    ncp-secret: t2zRuHRx0YXq1FJ1T1asB8uKOr3pqIIpFs2vP5tf